version: '1'
services:
  zookeeper: 
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # # Automatically creates required kafka topics if they were not created.
  # kafka-topics-creator:
  #   build:
  #     context: kafka-topic-creator
  #     dockerfile: Dockerfile
  #   container_name: kafka-topics-creator
  #   depends_on:
  #     - zookeeper
  #     - broker
  #   environment:
  #     ZOOKEEPER_HOSTS: "zookeeper:2181"
  #     KAFKA_TOPICS: "topic_v1 topic_v2"



  # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
  # bitnami/kafka just contains Apache Kafka. confluentinc/cp-kafka contains Confluent Community which is an additional platform built by Confluent which extends Apache Kafka
  # init-kafka:
  #   image: 'bitnami/kafka:latest'
  #   depends_on:
  #     - broker
  #   entrypoint: [ '/bin/sh', '-c' ]
  #   command: |
  #     "
  #     echo -e 'Blocks until kafka is reachable'
  #     opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
  #     "
